# -*- coding=UTF-8 -*-
# Code generated by auto-derby-plugin-generator 94139cf
# URL: https://natescarlet.github.io/auto-derby-plugin-generator/#/plugins/race
# Date: 3/20/2022, 9:32:23 AM

import auto_derby
from auto_derby import single_mode


from typing import Text, Dict, Tuple

_ACTION_NONE = 0
_ACTION_BAN = 1
_ACTION_LESS = 2
_ACTION_MORE = 3
_ACTION_PICK = 4

_DEFAULT_ACTION = _ACTION_BAN

_RULES: Dict[Tuple[int, Text], int] = {
    (21, "京都ジュニアステークス"): _ACTION_MORE,
    (23, "ホープフルステークス"): _ACTION_MORE,
    (24, "京成杯"): _ACTION_MORE,
    (28, "弥生賞"): _ACTION_MORE,
    (30, "皐月賞"): _ACTION_MORE,
    (32, "京都新聞杯"): _ACTION_MORE,
    (33, "東京優駿（日本ダービー）"): _ACTION_MORE,
    (34, "マーメイドステークス"): _ACTION_MORE,
    (36, "七夕賞"): _ACTION_MORE,
    (38, "小倉記念"): _ACTION_MORE,
    (40, "紫苑ステークス"): _ACTION_MORE,
    (41, "オールカマー"): _ACTION_MORE,
    (43, "菊花賞"): _ACTION_MORE,
    (44, "エリザベス女王杯"): _ACTION_MORE,
    (45, "ジャパンカップ"): _ACTION_MORE,
    (47, "有馬記念"): _ACTION_MORE,
    (48, "日経新春杯"): _ACTION_MORE,
    (49, "アメリカJCC"): _ACTION_MORE,
    (51, "ダイヤモンドステークス"): _ACTION_MORE,
    (52, "金鯱賞"): _ACTION_MORE,
    (53, "大阪杯"): _ACTION_MORE,
    (55, "天皇賞（春）"): _ACTION_MORE,
    (56, "新潟大賞典"): _ACTION_MORE,
    (58, "鳴尾記念"): _ACTION_MORE,
    (59, "宝塚記念"): _ACTION_MORE,
    (60, "函館記念"): _ACTION_MORE,
    (63, "札幌記念"): _ACTION_MORE,
    (64, "新潟記念"): _ACTION_MORE,
    (66, "京都大賞典"): _ACTION_MORE,
    (67, "天皇賞（秋）"): _ACTION_MORE,
    (69, "ジャパンカップ"): _ACTION_MORE,
    (70, "中日新聞杯"): _ACTION_MORE,
    (71, "有馬記念"): _ACTION_MORE,
}


class Plugin(auto_derby.Plugin):
    def install(self) -> None:
        class Race(auto_derby.config.single_mode_race_class):
            def score(self, ctx: single_mode.Context) -> float:
                ret = super().score(ctx)
                action = _RULES.get(
                    (ctx.turn_count(), self.name),
                    _DEFAULT_ACTION,
                )
                if self.grade == Race.GRADE_NOT_WINNING and not ctx.is_after_winning:
                    ret += 15
                    return ret
                if action == _ACTION_BAN:
                    ret = 0
                elif action == _ACTION_LESS:
                    ret -= 5
                elif action == _ACTION_MORE:
                    ret += 5
                elif action == _ACTION_PICK:
                    ret += 100
                return ret

        auto_derby.config.single_mode_race_class = Race


auto_derby.plugin.register(__name__, Plugin())